name: pedfi
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

  cupertino_icons: ^1.0.6
  flutter_iconly: ^1.0.2
  fl_chart: ^0.67.0
  meta: ^1.11.0
  supabase_flutter: ^2.5.1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  flutter_slidable: ^3.1.0
  chart_sparkline: ^1.0.15+1
  web_socket_channel: ^2.4.5
  currency_text_input_formatter: ^2.2.3
  url_launcher: ^6.2.6
  table_calendar: ^3.1.1
  collection: ^1.18.0
  quiver: ^3.2.1
  board_datetime_picker: ^1.6.5
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0
  internet_connection_checker_plus: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/categoryicon/
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
